#===- enumerations.py - Python Enumerations ------------------*- python -*--===#
#
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
#===------------------------------------------------------------------------===#

"""
Clang Enumerations
==================

This module provides static definitions of enumerations that exist in libclang.

Enumerations are typically defined as a list of tuples. The exported values are
typically munged into other types or classes at module load time.

All enumerations are centrally defined in this file so they are all grouped
together and easier to audit. And, maybe even one day this file will be
automatically generated by scanning the libclang headers!
"""

# Maps to CXTokenKind. Note that libclang maintains a separate set of token
# enumerations from the C++ API.
TokenKinds = [
    ('PUNCTUATION', 0),
    ('KEYWORD', 1),
    ('IDENTIFIER', 2),
    ('LITERAL', 3),
    ('COMMENT', 4),
]

# The different kinds of completion tokens, as well as an optional spelling, in
# case the spelling of that token kind is known in advance.
CompletionChunkKinds = [
    ('Optional', 0, None),
    ('TypedText', 1, None),
    ('Text', 2, None),
    ('Placeholder', 3, None),
    ('Informative', 4, None),
    ('CurrentParameter', 5, None),
    ('LeftParen', 6, '('),
    ('RightParen', 7, ')'),
    ('LeftBracket', 8, '['),
    ('RightBracket', 9, ']'),
    ('LeftBrace', 10, '{'),
    ('RightBrace', 11, '}'),
    ('LeftAngle', 12, '<'),
    ('RightAngle', 13, '>'),
    ('Comma', 14, ', '), # The spelling of a comma, is a comma plus a space.
    ('ResultType', 15, None),
    ('Colon', 16, ':'),
    ('SemiColon', 17, ';'),
    ('Equal', 18, '='),
    ('HorizontalSpace', 19, None),
    ('VerticalSpace', 20, None),
]

__all__ = ['TokenKinds', 'CompletionChunkKinds']
